### ISSUE TITLE
Logout user after login expire

### ISSUE THREAD

**Issue by salgado** [igarape/copcast-android#100]
Actually, when user login expires the app can't do some operations like send videos.
The log shows the following message: 
Token expirado 1444845199382 1445530249720

So, we need a mechanism to force logout when this event occurs.

**Comment by salgado** [comment]
duplicated from #74

**Comment by brunosiqueira** [comment]
related to igarape/mogi-server#41

**Comment by brunosiqueira** [comment]
@martelli I remember us talking about testing a request response and if it was unauthorized it would redirect to the login page. We did not pursue that, right?

**Comment by martelli** [comment]
@brunosiqueira It's implemented. It checks the /users/me URL at "onResume()" and issues a notified logout (logout with toast message) when an "unauthorized" is received.
The open point is: how should we handle the other cases (noConnection, badConnection etc.)? I thought it might be transitory and thus we should ignore.
