### ISSUE TITLE
Use FFmpeg for local encoding

### ISSUE THREAD

**Issue by martelli** [igarape/copcast-android#105]
The Android hardware encoding doesn't produce very small files and there is a lot of room for improvement. Tests on the server indicate that the final files can represent ~30% of the original size.

Thus, we should investigate the option of using FFmpeg on the mobile to re-encode the produces video files.

**Comment by brunosiqueira** [comment]
Try to encode the files before uploading them

**Comment by martelli** [comment]
Merged #107 to create a pipeline which will handle the reencoding and encryption on the mobile.

**Comment by martelli** [comment]
Encryption on the mobile is not desired, as the officer might have access to the footage. On the server, we cannot stream directly through the pipe, as the FFmpeg cannot work on a streamed MP4 file. The solution will be hardening the temporary directory, which is now configurable.

On the reencoding side, FFmpeg on the mobile proved itself very cpu intensive, thus taking too much time. The solution was to tune the MediaRecorder profile to mimic the FFmpef reencoding behaviour.
