### ISSUE TITLE
Secure uploaded files

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#107]
Uploaded videos are saved in the tmp directory in the server without cryptography.
Think about encrypting them in the mobile before upload

**Comment by martelli** [comment]
Issue #105 also handles videos on the mobile, so I'll try to tackle both.

**Comment by brunosiqueira** [comment]
You can also mark one as duplicated and close it

Em quinta-feira, 19 de novembro de 2015, Leandro Martelli <
notifications@github.com> escreveu:

> Issue #105 <https://github.com/igarape/copcast-android/issues/105> also
> handles videos on the mobile, so I'll try to tackle both.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/igarape/copcast-android/issues/107#issuecomment-158076858>
> .
>


-- 
Bruno Siqueira

**Comment by martelli** [comment]
#105 now contains both issues and this one became obsolete.
