### ISSUE TITLE
Upload resilience

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#109]
The way the Upload works is: tries to upload each file. If it succeeds or not, it goes to the next untill the list is covered.

We must think about a way for the upload to be retry other attempts in a more automatic way.

**Comment by martelli** [comment]
Now all uploads are serial tasks, which means the client only receives the return message when the server has finished the reencoding and encryption. To allow faster uploads without overloading the server, we will try using RabbitMQ to create reencoding/encryption queues. This would allow the client do immediately return after the file data has been sent.
