### ISSUE TITLE
GPS in IncidentForm not working propperly

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#113]

**Comment by martelli** [comment]
When the GPS is turned off, the "location" field comes with a text. When the GPS is ON, but the app couldn't get a location, it receives "0.0, 0.0".
We should make both situations consistent and I think "0.0, 0.0" should not be used, as it is a valid location, nonetheless.
Perhaps use 2 dashes "--" would indicate the absence of information.
