### ISSUE TITLE
Show keyboard on login screen

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#117]
The keyboard has to show up after any field is selected

**Comment by brunosiqueira** [comment]
If i go to the Settings Screen and go back to the login screen, then the keyboard do not show, unless I focus on the password field

**Comment by dborkan** [comment]
I just fixed the keyboard display when returning from settings in https://github.com/igarape/copcast-android/commit/42578a601105c3fdd392d78a1fdd26092e89b89b
