### ISSUE TITLE
Use keystore to identify device and sign all information sent to the API server

### ISSUE THREAD

**Issue by martelli** [igarape/copcast-android#126]
Currently we cannot determine if a mobile belongs to our system or not. Anyone with credentials could log into any device and start sending information. This means one could switch his/her mobile and go undetected using a "ghost" mobile. This "ghost" mobile could connect to a untrusted network or even run a tampered version of the Copcast application.

To avoid this situation, the idea is the use the Android KeyStore to store device identification information. 
In summary, each mobile will generate a pair of public/private keys and the public key would be stored into the server, along with its IMEI, during a device registration phase. During operations, the private key and the IMEI would be used to sign all information sent to the server, which would be able verify it, validating the device and SIM card used. If desired, it is possible to also send the applications certificate information, thus allowing the system to detect apk tampering.

In summary, we would:

- implement a signing mechanism using the android keystore.
- enhance the upload routines to sign all information sent to the server.
- create a device registration procedure, to generate the key pair and register the device into the server.
- implement a signature validation routine on the server, which would broadcast an alert in case of failure.

**Comment by mollyling** [comment]
Generally I'm quite supportive.

Some notes:
 * A tampered apk could return the cert from an untampered apk.  There generally isn't a way to tell if the app's been tampered with.  Roughly the same reason why DRM gets cracked easily enough.  
 * Having a quick look, I found [this](https://ecenter.custhelp.com/app/answers/detail/a_id/512/~/what-is-an-esn,-imei,-sim,-msn-(sn)-and-pin%3F) which seems to indicate that IMEI and SIM values are different -- the IMEI identifies the phone, and the SIM number indicates the sim card.  But you can get both programatically in android, so it's easy to do.  But the Android KeyStore makes sure that a registered private key never leaves the phone, so sending the IMEI is a little redundant.  If you're worried about people swapping SIMs, then sending the SIM card ID is useful.
 * Use elliptical curve cryptography for the keypair.  Smaller keys and less computation for the same security as RSA. EC256/P-256 are a good combination.  SHA256withECDSA should be good for signing.

**Comment by martelli** [comment]
@mollyling Thanks for the notes.

**Comment by brunosiqueira** [comment]
@martelli this is ongoing already, right?
