### ISSUE TITLE
power button to start live streaming

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#133]

**Comment by martelli** [comment]
@brunosiqueira  As we cannot override the power button, can we change the title to "volume button"?

**Comment by brunosiqueira** [comment]
@martelli we would have to change the incident button

**Comment by martelli** [comment]
@brunosiqueira I guess we are running out of buttons here.
Shouldn't the incident flag be regarded as a notofication to the backoffice crew to start watching live?

**Comment by brunosiqueira** [comment]
@martelli Makes sense
