### ISSUE TITLE
Not uploading even when charging

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#142]
This need to be verified if it is in fact a bug. Reported by a partner n South Africa

_Cellphone XXX does not upload videos when it is on charger “cant upload right. The phone need to be charging or battery status full”. I do not know why it provides this error even is on charger or fully charged._

**Comment by brunosiqueira** [comment]
@arthurvasconcelos esta issue na verdade o problema é a mensagem de erro. Ele pode estar carregando o celular, mas estar configurado para so usar o wifi e estar no 3g. As mensagens de erro precisam ser separadas:
1 - mensagem de erro para quando o celular nao esta carregando.
2 - mensagem de erro quando não está no wifi e o "wifi only" está ligado.

**Comment by arthurvasconcelos** [comment]
@brunosiqueira eu testei aqui na minha compilação do webrecorder e as mensagens já estão separadas... você consegue me dizer em qual cenário elas apareceram separadas?!
