### ISSUE TITLE
Problem with flow in the register/settings screen

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#152]
In a device already with the webrecorder branch configured:
1 - log in
2 - Select the settings screen in the menu
3 - use the device's back button to return to the main screen
RESULT: after a few seconds, the register screen appears again. If a I press the back button again, it goes back to the main screen

**Comment by brunosiqueira** [comment]
@martelli

**Comment by martelli** [comment]
Yep, already on the pipe.
Basically, I'll replace the server url config screen with the registration
screen.

**Comment by dborkan** [comment]
Related to https://github.com/igarape/copcast-android/issues/149

**Comment by dborkan** [comment]
Should be tested once https://github.com/igarape/copcast-android/issues/149 is finished
