### ISSUE TITLE
Wifi off popup showing up repeatedly. 

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#157]
If we have the wifi turned off, every time we resume the app, it shows a popup asking to turn the wifi on for better location.

If I resume and pause the app *N* times, then *N* popup windows shows over each other.

**Comment by dborkan** [comment]
Fixed in https://github.com/igarape/copcast-android/commit/997b07d0346f0c37ed675262a1141baee8a9ba7c
