### ISSUE TITLE
Error when requesting streaming (from admin) while paused

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#165]
![screenshot_2016-05-29-18-02-19 1](https://cloud.githubusercontent.com/assets/28031/15634931/90e629c4-25a6-11e6-9e77-c3e1cafc6fd6.png)

**Comment by martelli** [comment]
Tested by trying to start live streaming while paused.
No error occured, but the admin hasn't been notified.
Created issue #169 to address this issue and close this one.
