### ISSUE TITLE
Back button login out but not leavin the app

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#167]
The expected behavior of clicking the back button is:
- Click the button
- Shows the popup "are you sure you want to leave the app?"
- Click Yes
Result: Shows the login screen

Expected: it should logout and go back to the home screen of the device, closing the app

**Comment by dborkan** [comment]
@brunosiqueira any reason why this is back in the To Do pipeline?

**Comment by martelli** [comment]
If I recall correctly, just because it won't crash the app, but just
require another hit on "back".

**Comment by dborkan** [comment]
Not sure I understand.  In the past if you hit back from the main activity screen and then confirmed the message, it would close CopCast.  Now it doesn't close CopCast but just takes you back to the login screen.  Is that not what we want?  I could have it logout then also close the app, but I think that would be a bit surprising if the user just logged in and wanted to return to the previous screen.

**Comment by martelli** [comment]
I agree. Hitting back should not logout the user. But in this case we should suppress the message, because it suggests an actual logout.

Perhaps we should also change the "back" behaviour while on a mission?

**Comment by brunosiqueira** [comment]
@martelli @dborkan The way it worked before was login out and closing the app. It was a way to leave the app completely. But I am open for changing the behavior if you two believe it is misleading.

So we could have two options: (1) login out and leaving the login screen open (2) closing the app and keeping it logged. 

Thoughts?

**Comment by martelli** [comment]
@dborkan @brunosiqueira Since it seems safe to assume that one device is not usually shared between officers, I'd let it just close the window without logging out. If the officer were to handle the device over to another officer, then an explicit logout would be required.
This could also be a "deployment config" option, like the video playback.

**Comment by dborkan** [comment]
@martelli - I believe that's what the code did before I made the change https://github.com/igarape/copcast-android/commit/1bd4d6de10c18e03ef4bd842e8909542b3834c36 which does "(1) login out and leaving the login screen open".  Should I just undo that change?  If I undo the change is there anything that remains for this issue?

**Comment by brunosiqueira** [comment]
@dborkan It was not closing the app. Destroying the MainActivity was also leading back to the login screen.

**Comment by dborkan** [comment]
Hmm, on my Android phone the app was getting before I made my change, as a result of ```MainActivity.this.finish();```).  Maybe my phone was behaving differently or I had some old version of the code?

**Comment by brunosiqueira** [comment]
@dborkan I can undo your change here and test in the MotoX I have here. I'll let you know.

**Comment by martelli** [comment]
If you need, I have devices here with Android 4.4, 5.0 and 6.0.

**Comment by brunosiqueira** [comment]
@dborkan @martelli I just reverted Daniel's code and the behavior is the same: it goes back to the login screen. Does it work differently in your devices, @martelli ?

**Comment by brunosiqueira** [comment]
@dborkan @martelli I used the function MainActivity.this.finishAffinity(); to finalize all the activities and it is working in my MotoX. Could you guys test in the ones you have there?

**Comment by dborkan** [comment]
Just tried the latest Android code, now when I hit back on the MainActivity screen, I get the confirmation, then if I click Yes it exits the app.  When I open Copcast again it remembers my login so I am back in the MainActivity with the "Start Mission" button.

**Comment by brunosiqueira** [comment]
Perfect!

Bruno Siqueira

2016-06-22 16:58 GMT+01:00 dborkan <notifications@github.com>:

**Comment by martelli** [comment]
Back button leaves the app without logging out.
