### ISSUE TITLE
When entering pause state, send information to admin asking to close livestream window.

### ISSUE THREAD

**Issue by martelli** [igarape/copcast-android#169]
If the officer pauses the mission while live streaming, the admin live video will stop, but the window won't be closed.

**Comment by ebadran** [comment]
Worthwhile also provide a feedback to admin user when this happens, e.g.:

"Live streaming disabled by officer."

**Comment by arthurvasconcelos** [comment]
The notification asked by @ebadran were implemented in commit bfbfb9d1441330bc1ac930a46a14c1ea6e7551ff now when android user pause the mission the app need to send a signal to streamStopped throught socket.
