### ISSUE TITLE
Stard/End/Pause Quickly

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#184]
"If the user starts/ends/pauses mission too quickly, the app crashes.
A possible solution would be to disable buttons for a few seconds while the app is changing state (e.g. saving a video file)"

**Comment by ebadran** [comment]
I've tried to crash the app by repeatedly starting/ending/pausing/requesting to stream.
The app worked perfectly in all situations.

Closing this issue now.
