### ISSUE TITLE
Livestream button is getting stuck in states when mission is paused.

### ISSUE THREAD

**Issue by arthurvasconcelos** [igarape/copcast-android#190]
When app user pauses the mission the livestream button dont back to IDLE state.

*Using branch: webrecorder_handler in server.

![screenshot_2016-07-06-15-53-33](https://cloud.githubusercontent.com/assets/1286768/16630962/ef20b7fc-4392-11e6-83cc-86e7a27a89ba.png)
![screenshot_2016-07-06-15-53-59](https://cloud.githubusercontent.com/assets/1286768/16630961/ef1fe656-4392-11e6-9b39-95e279483383.png)

**Comment by brunosiqueira** [comment]
@arthurvasconcelos test with the commit in this issue. I commited in webrecorder branch #183 

https://github.com/igarape/copcast-android/issues/183
