### ISSUE TITLE
CC-01-001 Lack of Pinning for HTTPS connections (Medium)

### ISSUE THREAD

**Issue by cure53** [igarape/copcast-android#198]
It was found that, although the Copcast mobile app validates TLS certificates, it does not currently implement pinning to protect TLS communications. This weakness allows adversaries with the ability to forge a valid TLS certificate, trusted by the certificate store in the phone, to intercept and modify network communications without any warnings shown to the user. Please note that many governments and some companies are known to be able to have capabilities to sign any TLS certificate, for any domain in the internet, and hence intercept communications when Pinning is not implemented.

The examples below show some of the traffic that an attacker might be able to capture due to the lack of Pinning:

**Example 1:** Credentials, etc. capture via registration

**URL:**
https://pentest-api.mycopcast.com/registration

**Request:**
```
POST /registration HTTP/1.1
Accept-Charset: UTF-8
Content-Type: application/json;charset=UTF-8
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 5X Build/MMB29Q)
Host: pentest-api.mycopcast.com
Connection: close
Accept-Encoding: gzip
Content-Length: 356

{"public_key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkqXhdhJvMa3Vm9ajE6bCBipRRvi6KofmOitqo8NZ\nkUznFDZo\/k1jXjgkXyWaHHxHkksCW5N8XjrhpJGrPSrAYQ==\n","username":"abeadmin1","password":"12345678","imei":"000000000000000","simid":"00000000000000000000","mac":"MEYCIQCnszvxMCelzQohsj2MWMRYuiYQYusZkzIgDEeVBM1VGwIhANlz1MC8TfIK7P9KgtSgWdIc\n9JhZPLlBWh6GReOzYIFT\n"}
```

**Example 2:** Login credentials and token capture

**URL:**
https://pentest-api.mycopcast.com/token

**Request:**
```
POST /token HTTP/1.1
Accept-Charset: UTF-8
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 5X Build/MMB29Q)
Host: pentest-api.mycopcast.com
Connection: close
Accept-Encoding: gzip
Content-Length: 53

username=abedroid1&password=abc123%21%3F&scope=client
```

**Response:**
```
HTTP/1.1 200 OK
Server: nginx/1.9.4
Date: Mon, 25 Jul 2016 14:21:20 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 275
Connection: close
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization, Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
Vary: X-HTTP-Method-Override
ETag: W/"113-bgdrzICtVkHLb8Mi5sFCPA"

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxZTQ1NzQ5NS03MzVjLTRlNjAtOTA4MS01OWUwOGIyZTNmYjIiLCJleHAiOjIwNjk0NTY0MjA1NTZ9.ROUHWZP081jjIxm2EjYiauIFadR8sCub0yncNtlc8RQ","userId":"15","userName":"Abe Droid1","role":"mobile","language":"en","hasVideoPlayback":true}
```

It is recommended to implement Pinning. For more background about this and iOS as well as Android examples, please see the OWASP Pinning Cheat Sheet.

**Comment by kamalg19** [comment]
@brunosiqueira To fix this issue, sample android code is present at https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning
We need to include CA cert in app. Please attach CA certs which we are using to sign copcast api communication.

**Comment by kamalg19** [comment]
Good articles about https pinning are below:
https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning#Android
https://www.paypal-engineering.com/2015/10/14/key-pinning-in-mobile-applications/

Following best practice, only intermediate and root CA certificates are pinned. Leaf certificates are not pinned.

**Comment by kamalg19** [comment]
We need to keep updating CA certs in assets folder if new api server are supported like for BG.

**Comment by cure53** [comment]
Issue was fixed successfully, fix confirmed!
