### ISSUE TITLE
Control over voice calls

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#20]
- The second need for development from our side is the option to make a voice call from the hand-set to no more that three pre-loaded phone numbers (police, ES and DoCS) whilst the video is streaming. this will be used only in emergencies. Ideally the phone-call will also then be recorded and up-loaded (or down-loaded don't understand which is which). This will cut-out the need to carry the hand-set and two way radio. The ability to record voice when calling police in emergencies will be invaluable in our oversight function - Again is this possible or even part of the App you envisage ?

**Comment by martelli** [comment]
@brunosiqueira AFAIK, we won't be allowed to access audio data from a call.
