### ISSUE TITLE
Translate android terms to bulgarian

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#208]
Create a new translation option for the app with the Bulgarian terms in the attached file.

[App EN BG.docx](https://github.com/igarape/copcast-android/files/430481/App.EN.BG.docx)

**Comment by kamalg19** [comment]
[App EN BG_other_terms.docx](https://github.com/igarape/copcast-android/files/441428/App.EN.BG_other_terms.docx)

Adding file having new translations received.

**Comment by brunosiqueira** [comment]
@kamalg19 there are 3 new terms already to translate. Can you check with the representatives if they can translate it for us?
```

    <string name="device_orientation_description_disabled">Orientation cannot be changed while on a mission.</string>
    <string name="datetime_not_auto">Not allowed. Please set Date &amp; Time automatic to proceed further.</string>
    <string name="datetime_config">Config</string>
```

**Comment by kamalg19** [comment]
Sure, will do.

**Comment by kamalg19** [comment]
Attaching doc with new English terms. 

[App EN BG_other_terms (1).docx](https://github.com/igarape/copcast-android/files/452345/App.EN.BG_other_terms.1.docx)

**Comment by brunosiqueira** [comment]
@kamalg19 do you have a device with bulgaria language enabled? I would like to see some screenshots before closing the issue.

**Comment by kamalg19** [comment]
My personal phone have Bulgaria language and I tested these translations on
that. Do you want any particular screen's screenshot?

**Comment by brunosiqueira** [comment]
The IDLE screen, the mission started, paused, Setting screen and uploading.
Just to check if the layout is working fine.

Bruno Siqueira

2016-09-05 18:29 GMT+01:00 kamalg19 <notifications@github.com>:

> My personal phone have Bulgaria language and I tested these translations on
> that. Do you want any particular screen's screenshot?
>

**Comment by kamalg19** [comment]
Sure will attach screenshots by tonight.

**Comment by kamalg19** [comment]
Its funny that I am not able to send screenshots as we disabled screenshots for app on device as part of cure53 bug fix. I am attaching some pics taken from another phone. Let me know if they are good else I can temporarily enable screenshots to send you that.

![img_20160905_220329](https://cloud.githubusercontent.com/assets/8698001/18259798/03b1848c-73b6-11e6-810e-05a35bd8059e.jpg)
![img_20160905_220405](https://cloud.githubusercontent.com/assets/8698001/18259795/03adf038-73b6-11e6-96f0-238df5f125cf.jpg)
![img_20160905_220458](https://cloud.githubusercontent.com/assets/8698001/18259796/03ae489e-73b6-11e6-90bd-ee85ec01a39b.jpg)
![img_20160905_220527](https://cloud.githubusercontent.com/assets/8698001/18259799/03cb0e0c-73b6-11e6-8a5c-80d83c64fe7e.jpg)
![img_20160905_220556](https://cloud.githubusercontent.com/assets/8698001/18259797/03b04f72-73b6-11e6-8043-81159a460b3e.jpg)
