### ISSUE TITLE
Adapt code to Reverse Tethering

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#212]
The reverse tethering app we want to use (to enable uploading using USB) has a conflict with the local Android library that detects the current connection state

This is our code:

```
ConnectivityManager connMgr = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
NetworkInfo networkInfo = connMgr.getActiveNetworkInfo(); //This returns null.
```

This is the answer from the R.T. app dev:
```
This exact snippet is the problem.
When using my app for Internet access, there are multiple cases depending on the ReverseTethering mode setting and the API level:
1) When using Mode 1:
	a) On API level >= 21: getActiveNetworkInfo most often returns a NetworkInfo of type ConnectivityManager.TYPE_VPN
	b) On API levels below, null
2) When using Mode 2:
	Always null
```

We must correct the treatmento to enable upload even when returns getActiveNetworkInfo null or TYPE_VPN

**Comment by brunosiqueira** [comment]
@kamalg19 since you are testing this issue too, could you validate if it is working and then close/reopen it?

**Comment by kamalg19** [comment]
@brunosiqueira Tested uploading video from two copcast phones while connected to usb reverse tethering to ubuntu laptop.

Closing this issue.
