### ISSUE TITLE
Pinning documentation

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#215]
After the issue #198 is finalized, the documentation must include a new step to include the certificate in the client before deploying it.

**Comment by kamalg19** [comment]
Will add step about including certificates in two places:
1. Adding a note in server install doc to share root and intermediate CA certificates.
2. Adding note in copcast-android README.md file

Also, requested root and intermediate CA certs from Bulgaria for Bulgaria pilot.

**Comment by kamalg19** [comment]
1. Added note in server installation doc
2. Added note in README.md file of copcast-server
3. Added note in README.md file of copcast-android
4. Display https pinning failed error message to user in app.

**Comment by kamalg19** [comment]
Waiting for intermediate CA and root CA certificates from Bulgaria tech team.
