### ISSUE TITLE
Delete old videos

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#37]
Delete old videos that are kept for more than 90(or other limit) days in the server.
Flagged videos must be kept for 1 year.

The timeouts (90 days or 1 year) must actually be a configuration option.

There are two key points that should be taken in consideration:
* A background task that runs over every video, deletes them and marks them in the database as deleted.
* in the analytics interface, show a picture of a deleted video when it is marked as deleted.
* include a flag in the database to indicate that the video was deleted

**Comment by martelli** [comment]
Fixed small WHERE clause bug and permission granting (videos table) and verified that the files have been deleted.
