### ISSUE TITLE
Flag occurrence 

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#58]
Officers need the ability to easily flag a timestamp as important if something noteworthy (eg an incident of violence) happened. One implementation would be to add a flag simply by holding down the volume button, which would add a flag to the video in the admin interface (when the video is uploaded) and also email the commander with a deep link to the time in question.

**Comment by salgado** [comment]
Starting this issue by recording a timestamp on a new Flag table, after the user press volume button.

**Comment by brunosiqueira** [comment]
Duplicated of #92
