### ISSUE TITLE
Video encryption 

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#91]
Video stored in the smartphone memory is encripted and cannot be accessed from the device. Delete automatically once uploaded

**Comment by ebadran** [comment]
Are keeping this issue? Or should we just recommend that all departments should configure their smartphones to use the "Full Disk Encryption" feature from Android?

**Comment by brunosiqueira** [comment]
@ebadran Lets go with the full encryption. And recomend it in the protocols?
