### ISSUE TITLE
Register incident clicking a button or pressing volume down 

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#92]
The officer should be able to register important moments in the timeline to bring the attention of the commander.

He should be able to flag an incident in two ways:
* click a button in the interface when the officer is in a mission
* press the volume down of the phone to flag the incident.

Both ways should send the flag to the server and save it in the database.

It could also email the commander with a deep link to the time in question.

**Comment by brunosiqueira** [comment]
@martelli I tested the volume down pressing with the phone locked and the incident is not registered. It is like it looses the bind action.

The phone also has full encryption. Not sure if this interfere

**Comment by martelli** [comment]
Do you see any messages while in debug mode?

You could also try pressing it twice with a +1s interval to see what happens.
