### ISSUE TITLE
Replay the footage on site with the device.

### ISSUE THREAD

**Issue by ebadran** [igarape/copcast-android#94]
There is the need for traffic officers at Cape Town to recall or replay the footage on site with the device, to show a motorist and to alleviate conflict with motorists.

This would include only the footage recorded in the same day.

**Comment by brunosiqueira** [comment]
Remember to log in the history table after each officer watches the video.

**Comment by martelli** [comment]
Should the playback be rejected if the app can't sucessfully log to the history table?
Otherwise it would be trivial to set the phone into "flight mode", watch the videos and uninstall the app, as it never happened.

**Comment by brunosiqueira** [comment]
@martelli lets treat the log as we do with the history. It tries to send, it falls back to the json (sqllite) if it fails and send it later. I do not think it should block the user's action. @ebadran, what do you think?

**Comment by martelli** [comment]
@brunosiqueira My point is: it would be so easy to circumvent that it wouldn't be worth the effort implementing it.
