### ISSUE TITLE
Incident Reporting Form (for Cape Town Traffic Police)

### ISSUE THREAD

**Issue by ebadran** [igarape/copcast-android#95]
Digital Incident Reporting Form:

A digital form that is built into the Smart Policing Application, and may be accessed by officers from their smartphones. Data captured with the form will include:
- Location, date and time
- Type of violation:
    - Accident (Y/N)
         - Gravity (from 1 to 5x)
         - Number of injured (input number)
    - Fine (Y/N)
         - Type of fine (select from a set of options)
    - Arrest (Y/N)
         - Resistance (Y/N)
               - Argument (Y/N)
               - Use of force (Y/N)
               - Use of lethal force (Y/N)

**Comment by brunosiqueira** [comment]
Getting null information in the address

![image](https://cloud.githubusercontent.com/assets/28031/11095447/e8401fd4-888c-11e5-88b1-5c57e30e0c2b.png)
